### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Integer.intValue()'

### ISSUE THREAD

**Issue by AhmedbGayess** [ryanheise/just_waveform#5]
For starters, thanks for this great plugin.

I'm encountering a problem on Android only, when i extract the data from the audio file I get this error

`PlatformException(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, null, null)`

I'm using the same code from the example with a few modifications

```
final audioFile = File(widget.audioFilePath);

    try {
      final dir = await getApplicationDocumentsDirectory();
      final waveFile = File('${dir.path}/waveform.wave');

      JustWaveform.extract(
        audioInFile: audioFile,
        waveOutFile: waveFile,
        zoom: WaveformZoom.pixelsPerSecond(
          pixelPerSecond.ceil(),
        ),
      ).listen(_progressStream.add, onError: _progressStream.addError);
    } catch (err) {
      _progressStream.addError(e);
    }
```

I'm having this problem on an Android device on 9.0.

Many thanks.

**Comment by ryanheise** [comment]
Can you share the full logs?

**Comment by AhmedbGayess** [comment]
Yes sure, thanks for the quick response.

```
I/System.out(18165): extractor format = {sample-rate=44100, track-id=1, durationUs=4551120, mime=audio/mp4a-latm, profile=2, channel-count=1, csd-0=java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]}
I/System.out(18165): channel count = 1
I/System.out(18165): sample rate = 44100
I/System.out(18165): expected sample count = 200704
I/System.out(18165): samples per pixel: 678 = 44100 / 65
I/System.out(18165): scaled samples length = 592
E/libc    (18165): Access denied finding property "ro.kirin.product.platform"
E/HwExtendedCodec(18165): mime: audio/mp4a-latm matching compontent failed!
I/OMXClient(18165): IOmx service obtained
I/ACodec  (18165): In onAllocateComponent create compenent, codec name: OMX.google.aac.decoder
W/HwExtendedUtils(18165): hw configLocalPlayBack err = -2147483648
I/ACodec  (18165): onStart
W/System.err(18165): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
W/System.err(18165): 	at android.media.MediaFormat.getInteger(MediaFormat.java:979)
W/System.err(18165): 	at com.ryanheise.just_waveform.WaveformExtractor.processAudio(WaveformExtractor.java:141)
W/System.err(18165): 	at com.ryanheise.just_waveform.WaveformExtractor$ProcessThread.run(WaveformExtractor.java:71)
I/System.out(18165): invokeMethod onError(Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference)
W/ACodec  (18165): forcing OMX state to Idle when received shutdown in ExecutingState
```

**Comment by ryanheise** [comment]
Thanks, that is helpful. That means the error is occurring on this line (141):

```java
outFormat.setInteger(MediaFormat.KEY_BIT_RATE, inFormat.getInteger(MediaFormat.KEY_BIT_RATE));
```

which means that the input format didn't contain the `KEY_BIT_RATE` field. This should be guarded against nulls.

I will take a look at my next chance, but that may also give you some ideas on how to make your local copy work in the meantime.

**Comment by AhmedbGayess** [comment]
Thank you very much!

**Comment by ryanheise** [comment]
Hi @AhmedbGayess would you like to try the latest commit on `master`? Let me know if it works and I'll push out another release.

**Comment by ryanheise** [comment]
I'll close this since I committed that fix. If you still have the same issue with the latest release, comment below and I'll reopen.
